<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\program;

class ProgramSeeder extends Seeder{
    public function run(){
        program::create(['title' => 'Rumah Perlindungan bagi Anak','img' => 'crh.jpg','desc' => ' Rumah Perlindungan Anak ini merupakan rumah bagi anak-anak berprestasi namun dari keluarga tidak mampu atau yatim piatu.Anak-anak yang ada di CRH akan mendapatkan akomodasi dan fasilitas pendidikan secara gratis hingga tamat kuliah. Selain itu, Tangan Pengharapan juga menanamkan nilai-nilai kepemimpinan kepada setiap anak-anak agar mereka mampu dan siap untuk membawa perubahan di daerah mereka nantinya. Setelah mereka selesai kuliah, mereka akan kembali ke daerah masing-masing untuk membangun dan memajukan daerahnya sesuai dengan Visi dan Misi Tangan Pengharapan. Terdapat 4 CRH yang teresebar di 3 wilayah, yaitu Jakarta, Pulau Timor, dan Merauke.']);
        program::create(['title' => 'Makan untuk Belajar','img' => 'feed1.jpg','desc' => ' Tingginya angka putus sekolah dan banyaknya sekolah yang tutup karena tidak ada guru yang mengajar, serta ancaman gizi buruk pada anak karena kemiskinan, mendorong Tangan Pengharapan membuka Feeding and Learning Center yang tersebar di pedalaman Indonesia. Tangan Pengharapan memberikan makanan bergizi 3 kali dalam seminggu dan pendidikan secara gratis. Pemberian makanan bergizi bertujuan agar mereka tetap dapat berkonsentrasi dalam belajar dan terhindar dari ancaman gizi buruk.']);
        program::create(['title' => 'Sekolah Keterampilan','img' => 'lst.jpg','desc' => 'Life Skill Training merupakan salah satu Program Yayasan Tangan Pengharapan untuk meningkatkan kemampuan anak-anak di pedalaman melalui komputer dan bahasa Inggris. Keterbatasan fasilitas dan tidak adanya pelajaran komputer membuat mereka masih tertinggal. Melalui Program Life Skill Training Computer, Tangan Pengharapan membuka Sekolah Keterampilan dengan menyediakan fasilitas komputer dan tenaga pengajar secara gratis bagi peserta yang mendaftar program ini bagi anak-anak di pedalaman agar mereka dapat meningkatkan kemampuan mereka. Sehingga mereka mendapatkan sertifikat pelatihan di akhir pertemuan.']);
        program::create(['title' => 'Pendidikan Anak Usia Dini','img' => 'rt1.jpg','desc' => 'Membangun masa depan yang cerah untuk generasi Indonesia merupakan tujuan utama didirikannya PAUD (Pendidikan Anak Usia Dini) Tangan Pengharapan di beberapa titik. PAUD adalah jenjang pendidikan sebelum jenjang pendidikan Sekolah Dasar yang diberikan kepada anak yang berusia 4-6 tahun. Pada usia emas yaitu umur 0-6 tahun adalah pembentukan karakter dan pendidikan yang bagus bagi anak untuk bisa melanjutkan pendidikan ke jenjang yang lebih tinggi. Tangan Pengharapan berupaya untuk mempersiapkan anak mencapai kesiapan belajar di sekolah sehingga mampu melanjutkan ke jenjang pendidikan selanjutnya dengan memberikan materi pelajaran yang berkualitas dan membantu pertumbuhan dan perkembangan jasmani dan rohani anak.']);
        program::create(['title' => 'Sponsor Guru Pedalaman','img' => 'rt.jpg','desc' => ' Sebagai kontribusi bagi dunia pendidikan di Indonesia, Tangan Pengharapan mengirimkan tenaga-tenaga pengajar berkualitas, guru-guru berstrata 1 untuk mengajar di center-center Tangan Pengharapan, di sekolah-sekolah negeri yang kekurangan guru di pedalaman. Demi meningkatkan kualitas pendidikan yang merata di pelosok Indonesia, serta meningkatkan kualitas dan teknik mengajar para guru di seluruh pelosok negeri, Tangan Pengharapan juga mengadakan pelatihan guru. "Training for teachers" yaitu pelatihan bagi guru-guru pedalaman YTP yang dilaksanakan dibeberapa titik. Pelatihan ini diadakan untuk memperbaharui ilmu, metode, semangat dan motivasi guru-guru dalam mengajar. Selama tahun 2018, melalui kegiatan Pelatihan Guru Pedalaman, Tangan Pengharapan sudah memberikan pelatihan kepada 541 guru di 3 tempat yaitu Nias, Kupang, dan TTS.']);
        program::create(['title' => 'Fasilitas Pendidikan','img' => 'causes-3.jpg','desc' => ' Anak-anak dipedalaman harus menahan keinginan mereka untuk bisa memiliki tas dan sepatu yang layak. Jangankan membeli sepatu untuk makan sehari-hari saja mereka terkadang tidak mampu. Tak jarang banyak anak-anak di pedalaman yang tidak menggunakan sepatu untuk pergi ke sekolah dan menggunakan kantong plastik untuk membawa buku-buku mereka. Kurangnya fasilitas pendidikan yang dimiliki oleh anak-anak di pedalaman mendorong Tangan Pengharapan untuk memberikan fasilitas pendidikan berupa bangunan sekolah, sepatu, tas, alat tulis dan buku, pakaian layak pakai, alat musik, buku bacaan, seragam sekolah, sikat gigi, dan sandal. Donasi diberikan kepada anak-anak yang ada di Feeding and Learning Center Tangan Pengharapan.']);
        program::create(['title' => 'Sekolah Penjara','img' => 'ps1.jpg','desc' => ' Sekolah penjara merupakan salah satu program pendidikan yang mendukung nak-anak kurang beruntung yang sedang dibina di lapas. Anak akan dibina dalam 3 hal yaitu Life Skill Training (LST), Pusat Kegiatan Belajar Masyarakat (PKBM), dan konseling/foto karakter (Power Character).Keterampilan yang diberikan adalah pijat refleksi, barista, bakery, YTP juga membuka perpustakaan yang dapat mendukung KBM anak. Selain itu Tangan Pengharapan juga memberikan makanan bergizi satu kali dalam seminggu. Kerjasama dengan LPKA Salemba sudah dilakukan sejak bulan Maret 2017 lalu. Selain LPKA Salemba, kerjasama ini juga dilakukan dengan Lapas Wanita Klas IIA Pondok Bambu, Jakarta. Di Lapas Wanita, para warga binaan diberikan keterampilan komputer sebagain bekal mereka bila sudah selesai dari pembinaan lapas.']);
        program::create(['title' => 'Pusat Pelatihan dan Pengembangan','img' => 'ltc.jpg','desc' => 'Pemberdayaan masyarakat ini bertujuan untuk mengeluarkan masyarakat yang ada dipedalaman dari kemiskinan, melatih masyarakat mengembangkan potensi sumber daya alam dan sumber daya manusia di bidang pertanian, peternakan, peningkatan hasil tani, dan pembuatan water tank untuk mengatasi kekeringan.']);
        program::create(['title' => 'Klinik Berjalan','img' => 'mc.jpg','desc' => ' Dengan klinik berjalan, Tangan Pengharapan dapat menjangkau daerah pedalaman untuk menolong masyarakat yang kurang mampu supaya bisa mendapatkan pelayanan kesehatan dengan cepat dan gratis.Mobile Clinic merupakan sebuah pelayanan kesehatan secara gratis yang dilakukan di wilayah Pulau Timor, Nusa Tenggara Timur dengan konsep klinik berjalan. Dengan medan yang sulit dan jauh dari fasilitas kesehatan, Mobile clinic menjangkau pelosok desa dua kali dalam seminggu. Penyakit yang sering ditemui ketika pengobatan adalah ISPA (Infeksi Saluran Pernafasan), gatal-gatal, hipertensi, katarak, tumor, dan beberapa penyakit lainnya. Selain pengobatan, tim Mobile Clinic juga melakukan edukasi mengenai kesehatan agar masyarakat sadar akan pentingnya menjaga kesehatan dan memiliki gaya hidup yang sehat.']);
    }
}
